language: php
php:
  - 5.3
  - 5.4

before_script:
  - phpenv rehash
  - composer install --dev

script:
  - phpunit
  - example/demo _meta --zsh commit arg 0 suggestions
  - example/demo _meta --zsh commit arg 1 valid-values

notifications:
  webhooks:
    - http://wireroom.extremedev.org/=/travis-ci/Hall
